name: Deploy PWA to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Move /public contents to root (keeps your structure intact)
      - name: Move public files to root
        run: |
          mv public/* .
          mv public/.gitkeep . || true  # Optional: Preserve .gitkeep if exists

      # 3. Deploy to GitHub Pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Deploy from root (where we moved the files)
