name: Deploy PWA to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is crucial for pushing to gh-pages
    steps:
      - uses: actions/checkout@v4
      
      - name: Move public files to root
        run: |
          mv public/* .
          mv public/.gitkeep . || true

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages  # Explicitly set this
